### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ZiGaMi** [GeneralEmbeddedCLibraries/boot#3]
- [x] Boot<->app interface data structure definition
- [x] Bootloader FSM logic
- [x] Boot back-door entry mechanism
- [x] Reset counter

**Comment by ZiGaMi** [comment]
DONE
